sudo: required
dist: trusty
group: edge
language: php

services:
  - docker

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - VARNISH_VERSION=5.0.0
    VARNISH_MODULES_VERSION=0.11.0
    NGINX_VERSION=1.9.15
    NGINX_CACHE_PURGE_VERSION=2.3

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.7.* VARNISH_VERSION=3.0.0 COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: VARNISH_VERSION=4.1.5

branches:
  only:
    - master
    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
    - '/^\d+\.\d+$/'

before_script:
  - sed -i -e "s/FROM .*/FROM php:${TRAVIS_PHP_VERSION}-alpine/" docker/Dockerfile
  - env > docker/.env
  - docker build -t "friendsofsymfony/http-cache-ci:php-${TRAVIS_PHP_VERSION}" docker/
  - sudo apt-get install -qq python-sphinx enchant
  - sudo pip install -r doc/requirements.txt

script:
  - docker run -v `pwd`:/app "friendsofsymfony/http-cache-ci:php-${TRAVIS_PHP_VERSION}" sh -c "varnishd -f /app/tests/Functional/Fixtures/varnish/fos.vcl -p vcl_dir=/app/tests/Functional/Fixtures/varnish/"
  - docker run -v `pwd`:/app "friendsofsymfony/http-cache-ci:php-${TRAVIS_PHP_VERSION}" sh -c "composer update $COMPOSER_FLAGS --prefer-source --no-interaction && vendor/bin/phpunit --coverage-clover=coverage.clover"
  - make -C doc SPHINXOPTS='-nW' html
  - make -C doc spelling

after_script:
  # avoid uploading the code coverage for PHP 7 and HHVM as they cannot generate it (PHPUnit dropped the old HHVM driver
  # and the XDebug API is not implemented in HHVM 3.5) and we don't want to cancel the Scrutinizer analysis by notifying
  # it than no coverage data is available
  - if [[ "$TRAVIS_PHP_VERSION" != "7" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
